version: '2'

services:

  page-home:
    container_name: page-home
    hostname: page-home
    build:
      context: flask/page-home
      dockerfile: Dockerfile
    working_dir: /app
    command: python page-home.py
    expose:
      - "80"

  page-product:
    container_name: page-product
    hostname: page-product
    build:
      context: flask/page-product
      dockerfile: Dockerfile
    working_dir: /app
    command: python page-product.py
    expose:
      - "80"

  page-about:
    container_name: page-about
    hostname: page-about
    build:
      context: flask/page-about
      dockerfile: Dockerfile
    working_dir: /app
    command: python page-about.py
    expose:
      - "80"

  nginx-controller:
    container_name: nginx-controller
    hostname: nginx-controller
    build:
      context: nginx/
      dockerfile: Dockerfile
    command: service nginx start
    links:
      - page-home
      - page-product
      - page-about
    ports:
      - "8888:80"
